# Generated by Django 4.2.30 on 2026-05-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200)),
                ('total_reports', models.IntegerField(default=0)),
                ('completed_reports', models.IntegerField(default=0)),
                ('pending_reports', models.IntegerField(default=0)),
                ('active_volunteers', models.IntegerField(default=0)),
                ('generated_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_date'],
            },
        ),
    ]
